export enum AppResponseError {
    NoError = 0,
    Unknown = 1,
    ServerError = 2,
    Banned = 3,
    RateLimit = 4,
    NotFound = 5,
    WrongType = 6,
    NoTeam = 7,
    NoClan = 8,
    NoMap = 9,
    NoCamera = 10,
    NoPlayer = 11,
    AccessDenied = 12,
    PlayerOnline = 13,
    InvalidPlayerid = 14,
    InvalidId = 15,
    InvalidMotd = 16,
    TooManySubscribers = 17,
    NotEnabled = 18,
    MessageNotSent = 19
}
